[[redirects]]
  from = "/api/*"
  to = "https://api.freeapi.app/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.*(\\.js|\\.css|\\.svg)$"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assests/*"
  to = "/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true
